version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
